micronaut.application.name=mimbre

# Habilitar el servicio de archivos est�ticos
micronaut.router.static-resources.default.paths=classpath:public
micronaut.router.static-resources.default.mapping=/**

# Configuraci�n de vistas (Pebble)
micronaut.views.pebble.enabled=true



# Configuracion de Base de Datos H2
datasources.default.url=jdbc:h2:file:./data/database;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
datasources.default.driverClassName=org.h2.Driver
datasources.default.username=sa
datasources.default.password=

datasources.default.dialect=H2
datasources.default.schema-generate=CREATE
