micronaut.application.name=mimbre

# Habilitar el servicio de archivos estáticos
micronaut.router.static-resources.default.paths=classpath:public
micronaut.router.static-resources.default.mapping=/**

# Configuración de vistas (Pebble)
micronaut.views.pebble.enabled=true


