package com.app;

import io.micronaut.context.event.StartupEvent;
import io.micronaut.runtime.event.annotation.EventListener;
import jakarta.inject.Singleton;

import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

@Singleton
public class DatabaseInitializer {

    private final DemoDataSeeder demoDataSeeder;

    public DatabaseInitializer(DemoDataSeeder demoDataSeeder) {
        this.demoDataSeeder = demoDataSeeder;
    }

    @EventListener
    public void onStartup(StartupEvent event) {
        File dataDir = new File("./data");
        if (!dataDir.exists()) {
            dataDir.mkdirs();
        }

        File initMarker = new File(dataDir, ".initialized");
        boolean isFirstRun = !initMarker.exists();

        ensureEmptyDatabaseExists();

        if (isFirstRun) {
            demoDataSeeder.seed();

            try {
                initMarker.createNewFile();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    private void ensureEmptyDatabaseExists() {
        File emptyDbFile = new File("./data/database_empty.mv.db");
        if (!emptyDbFile.exists()) {
            try (Connection conn = DriverManager.getConnection("jdbc:h2:file:./data/database_empty;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE", "sa", "")) {
                try (Statement stmt = conn.createStatement()) {
                    stmt.execute("CREATE TABLE IF NOT EXISTS CLIENTE (" +
                            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                            "nombre VARCHAR(255), ruc_documento VARCHAR(255), telefono VARCHAR(255), email VARCHAR(255), direccion VARCHAR(255))");

                    stmt.execute("CREATE TABLE IF NOT EXISTS PRODUCTO (" +
                            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                            "nombre VARCHAR(255), sku VARCHAR(255), precio DECIMAL(19, 2), stock INT, categoria VARCHAR(255))");

                    stmt.execute("CREATE TABLE IF NOT EXISTS PRODUCTO_CATEGORIA (" +
                            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                            "nombre VARCHAR(255), descripcion VARCHAR(255))");

                    stmt.execute("CREATE TABLE IF NOT EXISTS PROVEEDOR (" +
                            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                            "nombre VARCHAR(255), ruc VARCHAR(255), telefono VARCHAR(255), email VARCHAR(255), direccion VARCHAR(255))");

                    stmt.execute("CREATE TABLE IF NOT EXISTS VENTA (" +
                            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                            "numero_factura VARCHAR(255), cliente_id BIGINT, cliente_nombre VARCHAR(255), fecha TIMESTAMP, condicion VARCHAR(255), monto_total DECIMAL(19, 2), estado VARCHAR(255))");

                    stmt.execute("CREATE TABLE IF NOT EXISTS VENTA_DETALLE (" +
                            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                            "venta_id BIGINT, producto_id BIGINT, producto_nombre VARCHAR(255), cantidad INT, precio_unitario DECIMAL(19, 2), subtotal DECIMAL(19, 2))");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
}
